### ISSUE TITLE
Feedback Project 2

### ISSUE THREAD

**Issue by aldimahardiansyah** [Rad283/Projek_Bengkel_mobil#4]
Terima kasih telah mengerjakan Project 2.

### Berikut beberapa  feedback secara umum:

- Web sudah sesuai dengan tema yang telah ditetapkan.
- Web sudah menerapkan konsep RWD.
- Pada landing page ketika dibuka di handphone, humbergur menu dapat dibuka tetapi tidak dapat ditutup.
- Desain landing page masih terkesan kasar.
- Pada halaman admin terdapat beberapa bagian yang kurang maksimal, mulai dari desainnya, linknya, tata letaknya, dll.

### Saran:

- Untuk form lebih baik di tampung kedalam card.
- Landing page dapat menggunakan template gratis dari internet.
- Konten pada halaman admin lebih baik diberi margin pada card-nya.

> Semoga ilmunya bermanfaat dan bisa dikontribusikan pada hal yang lebih besar. Jangan pernah berhenti mencari dan menggembangkan minatnya, jika lelah koding silahkan istirahat tapi jangan berhenti dan menyerah.

Salam, Aldi Mahardiansyah.

**Comment by aldimahardiansyah** [comment]
@Wjdozky @Rad283 @shilamumtaz @ssintyaaa

**Comment by Rad283** [comment]
Baik, terima kasih banyak kang
